module InfisicalSDK
  class SecretsClient
    @command_runner: CommandRunner
    def initialize: (CommandRunner) -> void

    def get: (
        secret_name: String,
        project_id: String,
        environment: String,
        path: String?,
        include_imports: bool?,
        type: String?
      ) -> InfisicalSecret

    def list: (
        project_id: String,
        environment: String,
        path: String?,
        attach_to_process_env: bool?,
        expand_secret_references: bool?,
        recursive: bool?,
        include_imports: bool?,
      ) -> Array[InfisicalSecret]
    def update: (
        secret_name: String,
        secret_value: String,
        project_id: String,
        environment: String,
        path: String?,
        skip_multiline_encoding: bool?,
        type: String?
      ) -> InfisicalSecret
    def create: (
        secret_name: String,
        secret_value: String,
        project_id: String,
        environment: String,
        secret_comment: String?,
        skip_multiline_encoding: bool?,
        type: String?,
        path: String?
    ) -> InfisicalSecret
    def delete: (
        secret_name: String,
        project_id: String,
        environment: String,
        path: String?,
        type: String?,
      ) -> InfisicalSecret

    private
      def error_handler: (untyped) -> void
      def run_command: (untyped) -> untyped
  end
end
