# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dry-struct', '~> 1.6'
gem 'dry-types', '~> 1.7'
gem 'ffi', '~> 1.9', '>= 1.9.10'
gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.21'
gem 'rbs', '>= 3.5.2'
gem 'steep', '>= 1.7.1'
