pub const INFISICAL_UNIVERSAL_AUTH_CLIENT_ID_ENV_NAME: &str = "INFISICAL_UNIVERSAL_AUTH_CLIENT_ID";
pub const INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET_ENV_NAME: &str =
    "INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET";
pub const INFISICAL_GCP_AUTH_IDENTITY_ID_ENV_NAME: &str = "INFISICAL_GCP_AUTH_IDENTITY_ID";
pub const INFISICAL_GCP_IAM_SERVICE_ACCOUNT_KEY_FILE_PATH_ENV_NAME: &str =
    "INFISICAL_GCP_IAM_SERVICE_ACCOUNT_KEY_FILE_PATH";
