---
name: Build Python

on:
    workflow_call:
    workflow_dispatch:

jobs:
    generate_schemas:
        uses: ./.github/workflows/generate-schemas.yml

    bump-version:
        name: Version changes
        needs:
            - generate_schemas
            # - test-rust-crate
        runs-on: ubuntu-latest
        # if: startsWith(github.ref, 'refs/tags/')
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ github.head_ref }}

            - name: Install python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Bump versions (pyproject.toml / Cargo.toml)
              run: | # poetry version ${{ github.ref_name }}
                  cd ./crates/infisical-py
                  pip install poetry
                  poetry self add poetry-bumpversion
                  poetry version 2.1.8
                  cd ../..

            - name: Upload Cargo.toml artifact
              uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
              with:
                  name: Cargo.toml
                  path: ./crates/infisical-py/Cargo.toml
            - name: Upload pyproject.toml artifact
              uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
              with:
                  name: pyproject.toml
                  path: ./crates/infisical-py/pyproject.toml

            - name: Upload __init__.py artifact
              uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
              with:
                  name: __init__.py
                  path: ./crates/infisical-py/infisical_client/__init__.py

    setup:
        name: Setup
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    build:
        name: Building Python wheel for - ${{ matrix.settings.os }} - ${{ matrix.settings.target }}
        runs-on: ${{ matrix.settings.os || 'ubuntu-latest' }}
        needs:
            - generate_schemas
            - bump-version
            - setup
        env:
            #_PACKAGE_VERSION: ${{ github.ref_name }}
            _PACKAGE_VERSION: "2.1.8"
        strategy:
            fail-fast: false
            matrix:
                settings:
                    - os: macos-12
                      target: x86_64-apple-darwin

                    - os: macos-12
                      target: aarch64-apple-darwin

                    - os: windows-2022
                      target: x86_64-pc-windows-msvc

                    - os: ubuntu-22.04
                      target: x86_64-unknown-linux-gnu

                    - os: ubuntu-22.04
                      target: aarch64-unknown-linux-gnu

        steps:
            - name: Checkout repo
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

            - name: Setup Node
              uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
              with:
                  node-version: 18

            - name: Install rust
              uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248 # stable
              with:
                  toolchain: stable
                  targets: ${{ matrix.settings.target }}

            - name: Cache cargo registry
              uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
              with:
                  key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.os }}

                  #
                  #
                  #
                  #
                  #
                  #

            - name: Delete existing version files
              run: |
                  rm -rf ./crates/infisical-py/Cargo.toml
                  rm -rf ./crates/infisical-py/pyproject.toml
                  rm -rf ./crates/infisical-py/infisical_client/__init__.py

            - name: Download Cargo.toml artifact
              uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
              with:
                  name: Cargo.toml
                  path: ./crates/infisical-py/
            - name: Download pyproject.toml artifact
              uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
              with:
                  name: pyproject.toml
                  path: ./crates/infisical-py/

            - name: Download __init__.py artifact
              uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
              with:
                  name: __init__.py
                  path: ./crates/infisical-py/infisical_client/

            - name: Retrieve Type Definitions
              uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
              with:
                  name: schemas.py
                  path: ${{ github.workspace }}/crates/infisical-py/infisical_client/

                  #
                  #
                  #
                  #
                  #
                  #
                  #
                  #
                  #

            - name: Build wheels
              if: ${{ matrix.settings.target != 'x86_64-unknown-linux-gnu' }}
              uses: PyO3/maturin-action@a3013db91b2ef2e51420cfe99ee619c8e72a17e6 # v1.40.8
              with:
                  target: ${{ matrix.settings.target }}
                  args: --release --find-interpreter --sdist
                  sccache: "true"
                  manylinux: "2_28" # https://github.com/pola-rs/polars/pull/12211
                  working-directory: ${{ github.workspace }}/crates/infisical-py

            - name: Build wheels (Linux - x86_64)
              if: ${{ matrix.settings.target == 'x86_64-unknown-linux-gnu' }}
              uses: PyO3/maturin-action@a3013db91b2ef2e51420cfe99ee619c8e72a17e6 # v1.40.8
              with:
                  target: ${{ matrix.settings.target }}
                  args: --release --find-interpreter --sdist
                  container: quay.io/pypa/manylinux_2_28_x86_64:2023-11-20-745eb52
                  sccache: "true"
                  manylinux: "2_28" # https://github.com/pola-rs/polars/pull/12211
                  working-directory: ${{ github.workspace }}/crates/infisical-py

            - name: Upload wheels
              uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
              with:
                  name: infisical_python-${{ env._PACKAGE_VERSION }}-${{ matrix.settings.target }}
                  path: ${{ github.workspace }}/target/wheels/infisical_python*.whl

            - name: Upload sdists
              if: ${{ matrix.settings.target == 'x86_64-unknown-linux-gnu' }} # we only need one sdist
              uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
              with:
                  name: infisical_python-${{ env._PACKAGE_VERSION }}-sdist
                  path: ${{ github.workspace }}/target/wheels/infisical_python-*.tar.gz
