---
name: Build Node.js Bindings
run-name: Build Node.js Bindings

on:
    #pull_request:
    push:
        branches:
            - "test-workflows"
    #workflow_dispatch:
    workflow_call:

defaults:
    run:
        shell: bash
        working-directory: languages/node

jobs:
    #generate_schemas:
    #    name: Generate schemas
    #    uses: ./.github/workflows/generate-schemas.yml

    # test-rust-crate:
    #     uses: ./.github/workflows/rust-test.yml

    build:
        name: Building @infisical/sdk-napi for - ${{ matrix.settings.os }}
        runs-on: ${{ matrix.settings.os || 'ubuntu-latest' }}
        #needs:
        # - generate_schemas
        #- test-rust-crate
        strategy:
            fail-fast: false
            matrix:
                settings:
                    - os: macos-12
                      target: x86_64-apple-darwin
                      build: |
                          npm run build
                          strip -x *.node

                    - os: macos-12
                      target: aarch64-apple-darwin
                      build: |
                          npm run build-arm64
                          strip -x *.node

                    - os: windows-2022
                      target: x86_64-pc-windows-msvc
                      build: |
                          npm run build
                    - os: windows-2022
                      target: i686-pc-windows-msvc
                      build: |
                          rustup target add i686-pc-windows-msvc
                          npm run build-win-ia32

                    - os: ubuntu-22.04
                      target: x86_64-unknown-linux-gnu
                      build: |
                          sudo apt-get update &&
                          sudo apt-get install -y binutils &&
                          set -e &&
                          npm run build
                    - host: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                      docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:stable-2023-09-17-aarch64
                      build: |-
                          set -e &&
                          rustup target add aarch64-unknown-linux-gnu &&
                          npm run build --target aarch64-unknown-linux-gnu &&
        steps:
            - name: Checkout repo
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

            - name: Setup Node
              uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
              with:
                  node-version: 18

                  #cache: "npm"
                  #cache-dependency-path: languages/node/package-lock.json

            - name: Install rust
              uses: dtolnay/rust-toolchain@439cf607258077187679211f12aa6f19af4a0af7 # stable
              with:
                  toolchain: stable
                  targets: ${{ matrix.settings.target }}

            - name: Cache cargo registry
              uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1
              with:
                  key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.os }}

            #- name: Retrieve schemas
            #  uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
            #  with:
            #      name: schemas.ts
            #      path: ${{ github.workspace }}/languages/node/src/infisical_client/

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: ${{ matrix.settings.build }}

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: infisical.${{ matrix.settings.target }}.node
                  path: ${{ github.workspace }}/languages/node/infisical.*.node
                  if-no-files-found: error

            - name: Upload binding.js
              uses: actions/upload-artifact@v3
              with:
                  name: binding.js
                  path: ${{ github.workspace }}/languages/node/binding.js
                  if-no-files-found: error

            - name: Upload binding.d.ts
              uses: actions/upload-artifact@v3
              with:
                  name: binding.d.ts
                  path: ${{ github.workspace }}/languages/node/binding.d.ts
                  if-no-files-found: error
