name: Build Rust Cross Platform

on:
    workflow_call:

jobs:
    build_rust:
        name: Build for ${{ matrix.settings.os }} ${{ matrix.settings.target }}
        runs-on: ${{ matrix.settings.os }}
        strategy:
            fail-fast: false
            matrix:
                settings:
                    - os: macos-12
                      target: x86_64-apple-darwin
                    - os: macos-12
                      target: aarch64-apple-darwin
                    - os: windows-2022
                      target: x86_64-pc-windows-msvc
                    - os: ubuntu-22.04
                      target: x86_64-unknown-linux-gnu
                    - os: ubuntu-22.04
                      target: aarch64-unknown-linux-gnu

        steps:
            - name: Checkout
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

            - name: Install rust
              uses: dtolnay/rust-toolchain@439cf607258077187679211f12aa6f19af4a0af7 # stable
              with:
                  toolchain: stable

            - name: Cache cargo registry
              uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

            - name: Add build architecture
              run: rustup target add ${{ matrix.settings.target }}

            - name: Build Rust
              env:
                  RUSTFLAGS: "-D warnings"
              run: cargo build --target ${{ matrix.settings.target }} --release --workspace --exclude infisical-py # We have to exclude python due to a bug in pyo3 causing the build to fail on macos. We don't need the python bindings for the CI anyways.

            - name: Upload Artifact
              uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
              with:
                  name: libinfisical_c_files-${{ matrix.settings.target }}
                  path: |
                      target/${{ matrix.settings.target }}/release/*infisical_c*
