name: Release Java SDK
run-name: Release Java SDK

on:
    push:
        branches:
            - daniel/move-java-sdk

jobs:
    # generate_schemas:
    #     uses: ./.github/workflows/generate-schemas.yml

    # build_rust:
    #     uses: ./.github/workflows/build-c-bindings.yml

    # test-rust-crate:
    #     uses: ./.github/workflows/rust-test.yml
    #     secrets:
    #         INFISICAL_UNIVERSAL_CLIENT_SECRET: ${{ secrets.INFISICAL_UNIVERSAL_CLIENT_SECRET }}
    #         INFISICAL_UNIVERSAL_CLIENT_ID: ${{ secrets.INFISICAL_UNIVERSAL_CLIENT_ID }}
    #         INFISICAL_PROJECT_ID: ${{ secrets.INFISICAL_PROJECT_ID }}
    #         INFISICAL_SITE_URL: ${{ secrets.INFISICAL_SITE_URL }}

    build_java:
        name: Build Java
        runs-on: ubuntu-22.04
        needs:
            # - generate_schemas
            # - build_rust
            # - test-rust-crate

        steps:
            - name: Checkout Repository
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

            # - name: Download Java schemas artifact
            #   uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
            #   with:
            #       name: sdk-schemas-java
            #       path: languages/java/src/main/java/infisical/sdk/schema/

            - name: Setup Java
              uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
              with:
                  distribution: temurin
                  java-version: 21

            # - name: Download x86_64-apple-darwin files
            #   uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
            #   with:
            #       name: libinfisical_c_files-x86_64-apple-darwin
            #       path: languages/java/src/main/resources/darwin-x86-64

            # - name: Download aarch64-apple-darwin files
            #   uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
            #   with:
            #       name: libinfisical_c_files-aarch64-apple-darwin
            #       path: languages/java/src/main/resources/darwin-aarch64

            # - name: Download x86_64-unknown-linux-gnu files
            #   uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
            #   with:
            #       name: libinfisical_c_files-x86_64-unknown-linux-gnu
            #       path: languages/java/src/main/resources/linux-x86-64

            # - name: Download aarch64-unknown-linux-gnu files
            #   uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
            #   with:
            #       name: libinfisical_c_files-aarch64-unknown-linux-gnu
            #       path: languages/java/src/main/resources/linux-aarch64-gnu

            # - name: Download aarch64-unknown-linux-musl files
            #   uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
            #   with:
            #       name: libinfisical_c_files-aarch64-unknown-linux-musl
            #       path: languages/java/src/main/resources/linux-aarch64-musl

            # - name: Download x86_64-pc-windows-msvc files
            #   uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
            #   with:
            #       name: libinfisical_c_files-x86_64-pc-windows-msvc
            #       path: languages/java/src/main/resources/win32-x86-64

            # - name: Organize and rename Linux ARM64 libraries
            #   run: |
            #       mkdir -p languages/java/src/main/resources/linux-aarch64
            #       mv languages/java/src/main/resources/linux-aarch64-gnu/libinfisical_c.so languages/java/src/main/resources/linux-aarch64/libinfisical_c_gnu.so
            #       mv languages/java/src/main/resources/linux-aarch64-musl/libinfisical_c.so languages/java/src/main/resources/linux-aarch64/libinfisical_c_musl.so
            #       rm -rf languages/java/src/main/resources/linux-aarch64-musl
            #       rm -rf languages/java/src/main/resources/linux-aarch64-gnu

            - name: List files in resources folders
              run: |
                  echo "Listing files in languages/java/src/main/resources:"
                  ls -R languages/java/src/main/resources

            - name: Publish Maven
              uses: gradle/gradle-build-action@b5126f31dbc19dd434c3269bf8c28c315e121da2 # v2.8.1
              with:
                  arguments: publish
                  build-root-directory: languages/java
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
                  MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
