---
name: Release Node.js SDK
run-name: Release Node.js SDK

on:
    push:
        tags:
            - "*.*.*" # version, e.g. 1.0.0

concurrency:
    group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.sha }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash
        working-directory: languages/node

jobs:
    build-napi:
        uses: ./.github/workflows/build-napi.yml

    setup:
        name: Setup
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    npm:
        name: Publish NPM
        runs-on: ubuntu-22.04
        needs:
            - setup
            - build-napi
        steps:
            - name: Checkout repo
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

            - name: Setup Node
              uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
              with:
                  node-version: 18
                  cache: "yarn"
                  cache-dependency-path: yarn.lock

            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                  path: languages/node/artifacts

            - name: Copy schema and binding converter
              run: npm run copy:artifacts

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Set NPM version #get the version from the tag
              run: npm version ${{ github.ref_name }} --allow-same-version --no-git-tag-version

            - name: Run tsc
              run: npm run tsc

            - name: Setup NPM
              run: |
                  echo 'registry="https://registry.npmjs.org/"' > ./.npmrc
                  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ./.npmrc

                  echo 'registry="https://registry.npmjs.org/"' > ~/.npmrc
                  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            # - name: Pack NPM
            #   run: npm pack

            # - name: Publish NPM
            #   run: npm publish --tarball=./sdk-${{github.ref_name}}
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Move artifacts
              run: npm run artifacts

            - name: List packages
              run: ls -R ./npm
              shell: bash

            - name: List artifacts
              run: ls -R ./artifacts
              shell: bash

            #- name: Publish NPM
            #  run: npm publish --dry-run --access public --registry=https://registry.npmjs.org/
            #  env:
            #      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            #      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
