name: Test
run-name: Test

on:
    pull_request:
        types: [opened, synchronize]

    workflow_call:
        secrets:
            INFISICAL_UNIVERSAL_CLIENT_SECRET:
                required: true
            INFISICAL_UNIVERSAL_CLIENT_ID:
                required: true
            INFISICAL_PROJECT_ID:
                required: true
            INFISICAL_SITE_URL:
                required: true

jobs:
    test:
        name: Functional tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Rust
              uses: dtolnay/rust-toolchain@439cf607258077187679211f12aa6f19af4a0af7 # stable
              with:
                  toolchain: stable

            - name: 📦 Cargo test
              uses: actions-rs/cargo@v1
              env:
                  INFISICAL_UNIVERSAL_CLIENT_SECRET: ${{ secrets.INFISICAL_UNIVERSAL_CLIENT_SECRET }}
                  INFISICAL_UNIVERSAL_CLIENT_ID: ${{ secrets.INFISICAL_UNIVERSAL_CLIENT_ID }}
                  INFISICAL_PROJECT_ID: ${{ secrets.INFISICAL_PROJECT_ID }}
                  INFISICAL_SITE_URL: ${{ secrets.INFISICAL_SITE_URL }}
              with:
                  command: test
